// Code generated by xgen. DO NOT EDIT.

package cmsis_svd

import (
	"encoding/xml"
	"io"
)

// Range ...
type Range struct {
	XMLName xml.Name `xml:"range"`
	Minimum string   `xml:"minimum"`
	Maximum string   `xml:"maximum"`
}

// WriteConstraintType ...
type WriteConstraintType struct {
	XMLName             xml.Name `xml:"writeConstraintType"`
	WriteAsRead         bool     `xml:"writeAsRead"`
	UseEnumeratedValues bool     `xml:"useEnumeratedValues"`
	Range               *Range   `xml:"range"`
}

// AddressBlockType ...
type AddressBlockType struct {
	XMLName    xml.Name `xml:"addressBlockType"`
	Offset     string   `xml:"offset"`
	Size       string   `xml:"size"`
	Usage      string   `xml:"usage"`
	Protection string   `xml:"protection"`
}

// InterruptType ...
type InterruptType struct {
	XMLName     xml.Name `xml:"interruptType"`
	Name        string   `xml:"name"`
	Description string   `xml:"description"`
	Value       int      `xml:"value"`
}

// Usage ...
type Usage string

// RegisterPropertiesGroup ...
type RegisterPropertiesGroup struct {
	XMLName    xml.Name `xml:"registerPropertiesGroup"`
	Size       string
	Access     string
	Protection string
	ResetValue string
	ResetMask  string
}

// BitRangeLsbMsbStyle ...
type BitRangeLsbMsbStyle struct {
	XMLName xml.Name `xml:"bitRangeLsbMsbStyle"`
	Lsb     string
	Msb     string
}

// BitRangeOffsetWidthStyle ...
type BitRangeOffsetWidthStyle struct {
	XMLName   xml.Name `xml:"bitRangeOffsetWidthStyle"`
	BitOffset string
	BitWidth  string
}

// DimElementGroup ...
type DimElementGroup struct {
	XMLName      xml.Name `xml:"dimElementGroup"`
	Dim          string
	DimIncrement string
	DimIndex     string
}

// Region ...
type Region struct {
	XMLName     xml.Name `xml:"region"`
	EnabledAttr bool     `xml:"enabled,attr,omitempty"`
	NameAttr    string   `xml:"name,attr,omitempty"`
	Base        string   `xml:"base"`
	Limit       string   `xml:"limit"`
	Access      string   `xml:"access"`
}

// SauRegionsConfig ...
type SauRegionsConfig struct {
	XMLName                    xml.Name  `xml:"sauRegionsConfig"`
	EnabledAttr                bool      `xml:"enabled,attr,omitempty"`
	ProtectionWhenDisabledAttr string    `xml:"protectionWhenDisabled,attr,omitempty"`
	Region                     []*Region `xml:"region"`
}

// CpuType ...
type Cpu struct {
	XMLName             xml.Name          `xml:"cpu"`
	Name                string            `xml:"name"`
	Revision            string            `xml:"revision"`
	Endian              string            `xml:"endian"`
	MpuPresent          bool              `xml:"mpuPresent"`
	FpuPresent          bool              `xml:"fpuPresent"`
	FpuDP               bool              `xml:"fpuDP"`
	IcachePresent       bool              `xml:"icachePresent"`
	DcachePresent       bool              `xml:"dcachePresent"`
	ItcmPresent         bool              `xml:"itcmPresent"`
	DtcmPresent         bool              `xml:"dtcmPresent"`
	VtorPresent         bool              `xml:"vtorPresent"`
	NvicPrioBits        string            `xml:"nvicPrioBits"`
	VendorSystickConfig bool              `xml:"vendorSystickConfig"`
	DeviceNumInterrupts string            `xml:"deviceNumInterrupts"`
	SauNumRegions       string            `xml:"sauNumRegions"`
	SauRegionsConfig    *SauRegionsConfig `xml:"sauRegionsConfig"`
}

// EnumeratedValue ...
type EnumeratedValue struct {
	XMLName     xml.Name `xml:"enumeratedValue"`
	Name        string   `xml:"name"`
	Description string   `xml:"description"`
	Value       string   `xml:"value"`
	IsDefault   bool     `xml:"isDefault"`
}

// EnumeratedValuesType ...
type EnumeratedValuesType struct {
	XMLName         xml.Name           `xml:"enumeratedValuesType"`
	DerivedFromAttr string             `xml:"derivedFrom,attr,omitempty"`
	Name            string             `xml:"name"`
	Usage           string             `xml:"usage"`
	EnumeratedValue []*EnumeratedValue `xml:"enumeratedValue"`
}

// FieldType ...
type FieldType struct {
	XMLName                  xml.Name `xml:"fieldType"`
	DerivedFromAttr          string   `xml:"derivedFrom,attr,omitempty"`
	BitRangeLsbMsbStyle      *BitRangeLsbMsbStyle
	BitRangeOffsetWidthStyle *BitRangeOffsetWidthStyle
	Name                     string                  `xml:"name"`
	Description              string                  `xml:"description"`
	BitRange                 string                  `xml:"bitRange"`
	Access                   string                  `xml:"access"`
	ModifiedWriteValues      string                  `xml:"modifiedWriteValues"`
	WriteConstraint          *WriteConstraintType    `xml:"writeConstraint"`
	ReadAction               string                  `xml:"readAction"`
	EnumeratedValues         []*EnumeratedValuesType `xml:"enumeratedValues"`
}

// FieldsType ...
type FieldsType struct {
	XMLName xml.Name     `xml:"fieldsType"`
	Field   []*FieldType `xml:"field"`
}

// RegisterType ...
type RegisterType struct {
	XMLName                 xml.Name `xml:"registerType"`
	DerivedFromAttr         string   `xml:"derivedFrom,attr,omitempty"`
	DimElementGroup         *DimElementGroup
	RegisterPropertiesGroup *RegisterPropertiesGroup
	Name                    string               `xml:"name"`
	DisplayName             string               `xml:"displayName"`
	Description             string               `xml:"description"`
	AlternateGroup          string               `xml:"alternateGroup"`
	AlternateRegister       string               `xml:"alternateRegister"`
	AddressOffset           string               `xml:"addressOffset"`
	DataType                string               `xml:"dataType"`
	ModifiedWriteValues     string               `xml:"modifiedWriteValues"`
	WriteConstraint         *WriteConstraintType `xml:"writeConstraint"`
	ReadAction              string               `xml:"readAction"`
	Fields                  *FieldsType          `xml:"fields"`
}

// ClusterType ...
type ClusterType struct {
	XMLName                 xml.Name `xml:"clusterType"`
	DerivedFromAttr         string   `xml:"derivedFrom,attr,omitempty"`
	DimElementGroup         *DimElementGroup
	RegisterPropertiesGroup *RegisterPropertiesGroup
	Name                    string          `xml:"name"`
	Description             string          `xml:"description"`
	AlternateCluster        string          `xml:"alternateCluster"`
	HeaderStructName        string          `xml:"headerStructName"`
	AddressOffset           string          `xml:"addressOffset"`
	Register                []*RegisterType `xml:"register"`
	Cluster                 []*ClusterType  `xml:"cluster"`
}

// RegistersType ...
type RegistersType struct {
	XMLName  xml.Name        `xml:"registersType"`
	Cluster  []*ClusterType  `xml:"cluster"`
	Register []*RegisterType `xml:"register"`
}

// PeripheralType ...
type PeripheralType struct {
	XMLName                 xml.Name `xml:"peripheralType"`
	DerivedFromAttr         string   `xml:"derivedFrom,attr,omitempty"`
	DimElementGroup         *DimElementGroup
	RegisterPropertiesGroup *RegisterPropertiesGroup
	Name                    string              `xml:"name"`
	Version                 string              `xml:"version"`
	Description             string              `xml:"description"`
	AlternatePeripheral     string              `xml:"alternatePeripheral"`
	GroupName               string              `xml:"groupName"`
	PrependToName           string              `xml:"prependToName"`
	AppendToName            string              `xml:"appendToName"`
	HeaderStructName        string              `xml:"headerStructName"`
	DisableCondition        string              `xml:"disableCondition"`
	BaseAddress             string              `xml:"baseAddress"`
	AddressBlock            []*AddressBlockType `xml:"addressBlock"`
	Interrupt               []*InterruptType    `xml:"interrupt"`
	Registers               *RegistersType      `xml:"registers"`
}

// Peripherals ...
type Peripherals struct {
	XMLName    xml.Name          `xml:"peripherals"`
	Peripheral []*PeripheralType `xml:"peripheral"`
}

// VendorExtensions ...
type VendorExtensions struct {
	XMLName xml.Name `xml:"vendorExtensions"`
}

// Device ...
type Device struct {
	XMLName                 xml.Name `xml:"device"`
	SchemaVersionAttr       float64  `xml:"schemaVersion,attr"`
	RegisterPropertiesGroup *RegisterPropertiesGroup
	Vendor                  string            `xml:"vendor"`
	VendorID                string            `xml:"vendorID"`
	Name                    string            `xml:"name"`
	Series                  string            `xml:"series"`
	Version                 string            `xml:"version"`
	Description             string            `xml:"description"`
	LicenseText             string            `xml:"licenseText"`
	Cpu                     *Cpu              `xml:"cpu"`
	HeaderSystemFilename    string            `xml:"headerSystemFilename"`
	HeaderDefinitionsPrefix string            `xml:"headerDefinitionsPrefix"`
	AddressUnitBits         string            `xml:"addressUnitBits"`
	Width                   string            `xml:"width"`
	Peripherals             *Peripherals      `xml:"peripherals"`
	VendorExtensions        *VendorExtensions `xml:"vendorExtensions"`
}

func ReadSVD(reader io.Reader) (*Device, error) {
    device  := &Device{}
    decoder := xml.NewDecoder(reader)
    if err := decoder.Decode(device); err != nil {
		return nil, err
	}
	return device, nil
}
